# Generated by Django 4.2.6 on 2023-11-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_details_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_photo', models.ImageField(upload_to='picture')),
                ('client_location', models.CharField(max_length=100)),
                ('reviews', models.TextField()),
            ],
        ),
    ]
